{
 "title": "FritzBoxDashboard (Telegraf)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "measurement", "label": "Measurement", "query": "FritzBox" },
   { "name": "bucket", "label": "Bucket", "query": "tigstack" }
  ]
 },
 "panels": [
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ModelName\")\n  |> last()\n",
     "select": [
      [
       { "params": [ "ModelName" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteReceiveRate\")\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteReceiveRate\" then r._value * 8\n      else r._value,\n    })\n  )",
     "select": [
      [
       { "params": [ "ByteReceiveRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteSendRate\")\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteSendRate\" then r._value * 8\n      else r._value,\n    })\n  )",
     "select": [
      [
       { "params": [ "ByteSendRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteReceiveRate\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteReceiveRate\" then r._value * 8\n      else r._value,\n    })\n  )\n",
     "select": [
      [
       { "params": [ "ByteReceiveRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteSendRate\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteSendRate\" then r._value * 8\n      else r._value,\n    })\n  )\n",
     "select": [
      [
       { "params": [ "ByteSendRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Sync.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Current Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"Layer1DownstreamMaxBitRate\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"Layer1DownstreamMaxBitRate\" then r._value / 1024\n      else r._value,\n    })\n  )\n",
     "select": [
      [
       { "params": [ "Layer1DownstreamMaxBitRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ConnectionStatus\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "ConnectionStatus" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"Firmware\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "Firmware" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ExternalIPAddress\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "ExternalIPAddress" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "LAN Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsReceived\" and r.source == \"lan\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"LAN Downstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "lan" }
     ]
    },
    {
     "alias": "LAN Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsSent\" and r.source == \"lan\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"LAN Upstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "lan" }
     ]
    },
    {
     "alias": "WLAN 2.4 GHz Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsReceived\" and r.source == \"wlan_2.4GHz\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 2.4 GHz Downstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_2.4GHz" }
     ]
    },
    {
     "alias": "WLAN 2.4 GHz Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsSent\" and r.source == \"wlan_2.4GHz\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 2.4 GHz Upstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_2.4GHz" }
     ]
    },
    {
     "alias": "WLAN 5 GHz Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsReceived\" and r.source == \"wlan_5GHz\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 5 GHz Downstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsSent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_5GHz" }
     ]
    },
    {
     "alias": "WLAN 5 GHz Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"PacketsSent\" and r.source == \"wlan_5GHz\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 5 GHz Upstream\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "PacketsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_5GHz" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Sync.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Current Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"Layer1UpstreamMaxBitRate\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"Layer1UpstreamMaxBitRate\" then r._value / 1024\n      else r._value,\n    })\n  )\n",
     "select": [
      [
       { "params": [ "Layer1UpstreamMaxBitRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"DNSServers\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "DNSServers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"UpTime\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "UpTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ConnectionTime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ConnectionTime\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "ConnectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HostsActiveLAN\")\n  |> filter(fn: (r) => r[\"source\"] == \"network\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"LAN\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "HostsActiveLAN" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "2.4 GHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ClientsNumber\")\n  |> filter(fn: (r) => r[\"source\"] == \"wlan_2.4GHz\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 2.4Ghz\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "ClientsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_2.4GHz" }
     ]
    },
    {
     "alias": "5 GHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ClientsNumber\")\n  |> filter(fn: (r) => r[\"source\"] == \"wlan_5GHz\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN 5GHz\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "ClientsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_5GHz" }
     ]
    },
    {
     "alias": "Gast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ClientsNumber\")\n  |> filter(fn: (r) => r[\"source\"] == \"wlan_Guest\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN Guest\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "ClientsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "wlan_Guest" }
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteReceiveRate\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream\")\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteReceiveRate\" then r._value * 8\n      else r._value,\n    })\n  )\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "ByteReceiveRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ByteSendRate\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream\")\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"ByteSendRate\" then r._value * 8\n      else r._value,\n    })\n  )\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "ByteSendRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"LastError\")\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\", \"_field\", \"host\", \"status\"])\n  |> last()\n",
     "select": [
      [
       { "params": [ "LastError" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Downstream HEC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ATUCHECErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream HEC\")\n",
     "select": [
      [
       { "params": [ "ATUCHECErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Downstream CRC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ATUCCRCErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream CRC\")\n",
     "select": [
      [
       { "params": [ "ATUCCRCErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Downstream FEC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"ATUCFECErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream FEC\")\n",
     "select": [
      [
       { "params": [ "ATUCFECErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Upstream HEC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HECErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream HEC\")\n",
     "select": [
      [
       { "params": [ "HECErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Upstream CRC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CRCErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream CRC\")\n",
     "select": [
      [
       { "params": [ "CRCErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Upstream FEC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"FECErrors\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream FEC\")\n",
     "select": [
      [
       { "params": [ "FECErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TotalBytesReceived",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "1 hour",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesReceived64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"1 hour\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesReceived64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "1 day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesReceived64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"1 day\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesReceived64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "7 days",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -168h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesReceived64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"7 days\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesReceived64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DHCP Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hosts Active Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsActive\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Hosts Active Total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "Lan Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsActiveLAN\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Lan Active\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsActiveLAN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "WLAN Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsActiveWLAN\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"WLAN Active\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsActiveWLAN" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "Hosts Known Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsKnown\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Hosts Known Total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsKnown" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "Hosts Known LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsKnownLAN\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Hosts Known LAN\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsKnownLAN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    },
    {
     "alias": "Hosts Known WLAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"HostsKnownWLAN\" and r.source == \"network\")\n  |> drop(columns: [\"host\", \"source\"])\n  |> set(key: \"_field\", value: \"Hosts Known WLAN\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "HostsKnownWLAN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "network" }
     ]
    }
   ]
  },
  {
   "title": "Line Damping",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "Downstream Attenuation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"DownstreamAttenuation\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream Attenuation\")\n",
     "select": [
      [
       { "params": [ "DownstreamAttenuation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upstream Attenuation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"UpstreamAttenuation\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream Attenuation\")\n",
     "select": [
      [
       { "params": [ "UpstreamAttenuation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Downstream Noise Margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"DownstreamNoiseMargin\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Downstream Noise Margin\")\n",
     "select": [
      [
       { "params": [ "DownstreamNoiseMargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upstream Noise Margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"UpstreamNoiseMargin\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Upstream Noise Margin\")\n",
     "select": [
      [
       { "params": [ "UpstreamNoiseMargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TotalBytesSent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "1 hour",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesSent64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"1 hour\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "1 day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesSent64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"1 hour\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "7 days",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -168h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TotalBytesSent64\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"1 hour\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> last()\n\n",
     "select": [
      [
       { "params": [ "TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phone Calls Count Sum",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Missed Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountMissedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n  |> set(key: \"_field\", value: \"Missed Calls\")\n\n",
     "select": [
      [
       { "params": [ "CountMissedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Outgoing Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountOutCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Outgoing Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n",
     "select": [
      [
       { "params": [ "CountOutCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Received Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountReceivedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Received Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n",
     "select": [
      [
       { "params": [ "CountReceivedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phone Call Count History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Missed Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountMissedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Missed Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "CountMissedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Out Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountOutCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Out Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "CountOutCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Received Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"CountReceivedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Received Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "CountReceivedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phone Calls Time Sum",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Time Outgoing Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TimeOutCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Time Outgoing Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n\n",
     "select": [
      [
       { "params": [ "TimeOutCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Time Received Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TimeReceivedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Time Received Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n\n",
     "select": [
      [
       { "params": [ "TimeReceivedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phone Call Time History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Time Received Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TimeReceivedCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Time Received Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "TimeReceivedCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Time Outgoing Calls",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r._field == \"TimeOutCalls\")\n  |> drop(columns: [\"host\", \"_start\", \"_stop\", \"source\"])\n  |> set(key: \"_field\", value: \"Time Outgoing Calls\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n",
     "select": [
      [
       { "params": [ "TimeOutCalls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}